#**ARRAYS**

pip3 install array

**type conda prompt**

In [2]:
import array as arr

In [3]:
a=arr.array('i',[1,2,3,7,5])
b=arr.array('d',[1.2,3.0,5.4,9.5])

In [4]:
a


array('i', [1, 2, 3, 7, 5])

In [5]:
b

array('d', [1.2, 3.0, 5.4, 9.5])

In [6]:
len(a)

5

In [16]:
len(b)

4

In [17]:
a.append(83)

In [18]:
a

array('i', [1, 2, 3, 7, 5, 23, 23, 23, 83])

In [19]:
a.remove(3)

In [20]:
a

array('i', [1, 2, 7, 5, 23, 23, 23, 83])

In [21]:
b.append(4)

In [22]:
b

array('d', [1.2, 3.0, 5.4, 9.5, 4.0])

In [24]:
a[5]

23

In [25]:
b[3]

9.5

In [26]:
b.pop(3)

9.5

In [27]:
b

array('d', [1.2, 3.0, 5.4, 4.0])

In [31]:
a[::-1]

array('i', [83, 23, 23, 23, 5, 7, 2, 1])

In [35]:
b[0:-1]

array('d', [1.2, 3.0, 5.4])

In [37]:
a.index(2)

1

In [38]:
b.index(4)

3

In [39]:
a.insert(2,12)

In [40]:
a

array('i', [1, 2, 12, 7, 5, 23, 23, 23, 83])

In [52]:
c=arr.array('i',[3,5,9,0,45])

In [53]:
a+c

array('i', [1, 2, 12, 7, 5, 23, 23, 23, 83, 3, 5, 9, 0, 45])

#***NUMPY***

pip3 install numpy


In [61]:
import numpy as np

In [65]:
a=np.array([[1,2,3],[4,2,5],[7,6,9]])

In [66]:
a

array([[1, 2, 3],
       [4, 2, 5],
       [7, 6, 9]])

In [67]:
b=np.array([[4,2,2],[7,1,3],[4,2,34]])

In [68]:
b

array([[ 4,  2,  2],
       [ 7,  1,  3],
       [ 4,  2, 34]])

In [71]:
a.dtype

dtype('int32')

In [73]:
b.dtype

dtype('int32')

In [74]:
a.size

9

In [75]:
a[:2]

array([[1, 2, 3],
       [4, 2, 5]])

In [78]:
b[::-1]

array([[ 4,  2, 34],
       [ 7,  1,  3],
       [ 4,  2,  2]])

In [79]:
a+b

array([[ 5,  4,  5],
       [11,  3,  8],
       [11,  8, 43]])

In [80]:
a*b

array([[  4,   4,   6],
       [ 28,   2,  15],
       [ 28,  12, 306]])

In [81]:
a/b

array([[0.25      , 1.        , 1.5       ],
       [0.57142857, 2.        , 1.66666667],
       [1.75      , 3.        , 0.26470588]])

In [82]:
a-b

array([[ -3,   0,   1],
       [ -3,   1,   2],
       [  3,   4, -25]])

In [83]:
type(a)

numpy.ndarray

In [84]:
a.ndim

2

In [86]:
a.shape

(3, 3)

In [87]:
type(b)

numpy.ndarray

In [89]:
c=np.zeros((3,4))

In [90]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
d=np.array([[2,4,1],[7,5,4]],dtype ='float')

In [101]:
d

array([[2., 4., 1.],
       [7., 5., 4.]])

In [107]:
a.max()

9

In [108]:
b.min()

1

In [110]:
b.max()

34

In [115]:
a.max(axis=1)

array([3, 5, 9])

In [116]:
a.sum()

39

In [118]:
b.sum()

59

In [119]:
a.sort(axis=0)

In [120]:
a

array([[1, 2, 3],
       [4, 2, 5],
       [7, 6, 9]])

In [129]:
a.sort(axis=1)

In [131]:
a

array([[1, 2, 3],
       [2, 4, 5],
       [6, 7, 9]])

In [136]:
np.diag(a)

array([1, 4, 9])

In [138]:
np.diag(b)

array([ 4,  1, 34])

In [139]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 3.        ]])

In [140]:
np.sqrt(b)

array([[2.        , 1.41421356, 1.41421356],
       [2.64575131, 1.        , 1.73205081],
       [2.        , 1.41421356, 5.83095189]])

In [141]:
np.trace(a)

14

In [142]:
np.trace(b)

39

In [148]:
np.trace(a+b)

53